CMakeLists.txt
cmake/modules/macros.cmake

- parmmg as a sub project of a project
- uses modern cmake to set target_include_directories and install targets

various fixes for parmmg MmgTools/ParMmg#5

---

CMakeLists.txt

This fix is necessary for successfully compiling ParMmg on Windows with MinGW toolchain, cf. FreeFEM Jenkins [log](https://ci.inria.fr/freefem-dev/view/Windows/job/FreeFEM-sources-windows7-job5/161/consoleText).

Fix compilation on MinGW.

---

src/libparmmg_tools.c

warning: 'strncpy' specified bound depends on the length of the source argument

Fix -Wstringop-overflow

---

scripts/genheader.c

I believe this fixes an issue when trying to compile Fortran programs against ParMMG. This makes "libparmmgtypesf.h" similar to "libparmmgtypes.h" with regards to:
`#include "mmg/mmg3d/libmmgtypesf.h"`
as opposed to:
`#include "libmmgtypesf.h"`
which produces an error

genheader fix for Fortran header

---

src/libparmmg.h

Hi,
I believe the Fortran interface for real parameter inputs needs to be changed to match the function within ParMMG. Otherwise when using the Fortran API all variable inputs using pmmg_set_deparameter must be ints.
Cheers,
Iain

Change Fortran interface for real variable inputs.

---

src/quality_pmmg.c

```
==465872== Conditional jump or move depends on uninitialised value(s)
==465872==    at 0x8AE11F1: PMMG_qualhisto (quality_pmmg.c:251)
==465872==    by 0x8A9F516: PMMG_parmmglib1 (libparmmg1.c:911)
==465872==    by 0x8A9872E: PMMG_parmmglib_distributed (libparmmg.c:1616)
==465872==    by 0x5EE4C8E: DMAdaptMetric_ParMmg_Plex (parmmgadapt.c:269)
==465872==    by 0x636D661: DMAdaptMetric (dmgenerate.c:254)
==465872==    by 0x10F636: main (ex60.c:238)
==465872==  Uninitialised value was created by a stack allocation
==465872==    at 0x8AE0B13: PMMG_qualhisto (quality_pmmg.c:157)
```

qualhisto: jumps depend on uninitialised values

---

src/API_functions_pmmg.c
src/API_functionsf_pmmg.c
src/libparmmg.h
src/libparmmgtypes.h
src/parmmg.h

I've made three changes each relates to one of my commits:
1: Fixes of bugs in API Fortran interface.
2: Addition of a new function PMMG_Get_NodeCommunicatorsf. Differs from the original function as it only returns the shared node information for a given neighbouring partition. This is because Fortran does not have the functionality to create a pointer pointer with different memory allocations on each index. Therefore the original function was not usable and just segfaulted.
3: Addition of a check when recovering global node/triangle numbers to check they have been calculated. Previously they are only calculated if the mesh was saved to file which always done when using the API.
I have created the pull request to the feature/tetFromTria-API as it had some added API functions required for …

Changes to Fortran interface

---

src/locate_pmmg.c

```
==206307== Conditional jump or move depends on uninitialised value(s)
==206307==    at 0xC4A395C: PMMG_locatePoint_foundConvex (locate_pmmg.c:556)
==206307==    by 0xC4A3E9F: PMMG_locatePointBdy (locate_pmmg.c:689)
==206307==    by 0xC481C3B: PMMG_interpMetricsAndFields_mesh (interpmesh_pmmg.c:557)
==206307==    by 0xC482683: PMMG_interpMetricsAndFields (interpmesh_pmmg.c:717)
==206307==    by 0xC497EF3: PMMG_parmmglib1 (libparmmg1.c:830)
==206307==    by 0xC4913E3: PMMG_parmmglib_distributed (libparmmg.c:1744)
==206307==    by 0x617303F: DMAdaptMetric_ParMmg_Plex (parmmgadapt.c:277)
==206307==    by 0x63EFF57: DMAdaptMetric (dmgenerate.c:248)
==206307==    by 0x10FCCB: main (ex60.c:253)
```
Sadly, after using `feature/anisomet` (or a fresh `develop` since this is now merged) from …

Fix a conditional jump

---

src/inoutcpp_pmmg.cpp

Fix the input of `MMG3D_loadVtuMesh()` in `PMMG_loadVtuMesh_centralized()` in the file `src/inoutcpp_pmmg.cpp`. 
The input `sol` and `met` were switched.

Fix the input of MMG3D_loadVtuMesh() in PMMG_loadVtuMesh_centralized()

---

cmake/testing/pmmg_tests.cmake
src/libparmmg_tools.c

If the value of the level was not given as arguments, ParMmg was failing to identify the solution file as the level-set file.
This fix append the mmg arguments into `PMMG_parsar` to be able to support this.
Tests were also added.

If ls_val is not given in argument, need to go through mmg option parser

---

cmake/testing/pmmg_tests.cmake
src/inoutcpp_pmmg.cpp
src/libparmmg_tools.c
src/parmmg.c

1. In `inoutcpp_pmmg.c` file: Fix bug in `snprintf` in `PMMG_savePvtuMesh` and `PMMG_savePvtuMesh_and_allData`. `snprintf` cannot support to have input and output filename using the same variable. Use an intermediate filename to overcome this issue.
2. Fix typo in `inoutcpp_pmmg.c` file: `founded` -> `found` + update regex in accordance in `cmake/testing/pmmg_tests.cmake`.
3. For output file at `*.pvtu` format: 
- In `inoutcpp_pmmg.c` file: if the output filename has dots "." in the basename, replace them with dashes "-". Why? In VTK function SetFileName(filename), the first dot "." in the filename is interpreted as the extension start. So, whatever the user specifies after the first dot "." will be ignored by VTK. To overcome this, dots are replaced by dashes. 
- In `parmmg.c` file: a …

Fix some bugs in *.pvtu output

---

cmake/testing/pmmg_tests.cmake
src/analys_pmmg.c
src/parmmg.h
src/tag_pmmg.c

**Update the point tag with `MG_REF` if the edge in xtetra is `MG_REF` in the analysis update.** 
After load balancing, the analysis need to be updated (`PMMG_update_analys`), in particular, the point tag might not be up to date regarding the tag `MG_REF`. Indeed, if in the input distributed meshes one `Edge` is also a `ParallelEdge`, the tag `MG_REF` to the point is not assigned properly by the analysis because parallel interfaces are systematically skipped (for example, see condition  `if(((pt->tag[i] & MG_PARBDY) && !(pt->tag[i] & MG_PARBDYBDY)) || (pt->tag[i] & MG_BDY) ) continue;` in `MMG5_setadj`). This is not an issue in the first iteration, however after the load balancing and in the second iteration, point tags need to be up to date. To do so, the function …

Update point tag with MG_REF if the edge in xtetra is MG_REF + ci tests associated

---

cmake/testing/pmmg_tests.cmake
src/mergemesh_pmmg.c
src/mpipack_pmmg.c
src/mpiunpack_pmmg.c
src/tools_pmmg.c

1. Replace `memcopy` by `PMMG_copy_mmgInfo` function to copy mesh information when merge the mesh in `PMMG_mergeParmesh_rcvParMeshes`. `memcopy` was copying the pointer address only and was leading to double free error.
2. Modify `PMMG_copy_mmgInfo` to now update correctly the copy of `mesh->info.mat`, `mesh->info.invmat.lookup` and `mesh->info.par` arrays when we have a `*mmg3d` input file (local parameters or LS multimat references).
3. Modify `PMMG_mpisizeof_filenames`, `PMMG_mpipack_infos` and `PMMG_mpiunpack_infos` to take into account `mesh->info.invmat` data correctly as the structure `MMG5_InvMat` was added to mmg after the initial creation of this function in ParMmg.
4. Add ci tests to ensure the input file `*mmg3d` is read correctly for centralized/distributed input and …

Copy mesh information of local parameters or LS reference (multimat)

---

src/communicators_pmmg.c
src/zaldy_pmmg.c

Change type of `rtorecv` and `rtosend` variables in `PMMG_resize_extCommArray` and `PMMG_parmesh_ext_comm_free` functions. 
Type was `int` while it should have been `double`.

Modify type of rtorecv and rtosend variables

---

src/libparmmg_tools.c

In the help of ParMmg, add that it exists the option `-f` to specify the name of the file `*mmg3d` for multimat or local parameters.

Add -f option in the help of ParMmg

---

src/ls_pmmg.c

For now (until the overlap), the multimat mode does not support the `nosplit` option in `*.mmg3d` file.
This PR raises a warning and stops the code if the option `nosplit` is used.

Abort if `nosplit` option used in multimat mode

---

.github/workflows/main-job.yml

This PR allows to have two jobs that can be triggered independently in case of failure:
- the ParMmg configuration, build and tests;
- the coverage submission.
As the coverage submission randomly fails with no reason, it allows to retry the submission from the github interface without running the entire ParMmg tests.

Dedicated job for coverage submission.

---

src/analys_pmmg.c

Prior to this update, edge owners were chosen as the lowest rank proc owning the edge. This could cause discrepancy with orientation rules for physical triangles, in the case where the lowest rank proc sees all the physical triangles as not well-oriented. This would cause the data relative to normal vectors not to be computed by any procs.
This update changes the owner assignement rule: owner is now the lowest rank proc among those who see the face as well oriented. 
Added a function that check that among the whole mesh, every parallel edge has one and only one owner.

Modified rule for assigning parallel edge owners

---

CMakeLists.txt
src/mergemesh_pmmg.c
src/parmmg.h

The displacements argument to MPI_Gatherv() in PMMG_gather_parmesh() overflows when the combined packed mesh size exceeds 2^31. This commit does not solve the problem but it produces the right error message and an MPI_Abort() before an allocation error would occur. It also changes MEM_CHK_AVAIL to show the allocation size when an allocation fails, to make this kind of situation easier to diagnose.
Btw it looks like the size limit of ParMmg is actually smaller than that of mmg3d compiled with 32-bit indices; I encountered this problem with an input that takes 1.6GB storage while with mmg3d I have successfully treated a mesh that took 6.3GB storage. Also in terms of vertices and tetrahedra that mesh was much larger.
Of all possible solutions for this problem, I think the best would be to …

Diagnose gatherv overflow

---

.github/workflows/main-job.yml

gfortran-11 compiler is not installed anymore on MacOS-12 runner of github -> replace it by gfortran-14

Update gfortran version after modification of Macos-12 runner.

---

src/inout_pmmg.c

If both parallel nodes and parallel faces are provided, only parallel faces are kept for building communicators, regardless of order of data in input files.

API_DISTRIB_FACES prioritized over API_DISTRIB_NODES

---

cmake/testing/pmmg_tests.cmake
src/ls_pmmg.c

Enable value snapping in distributed ls discretization mode only when `PMMG_SNAPVAL`environment variable is defined (implementation of the distributed value snapping is in progress).

Disable value snapping (implementation in progress)
